.TH "Enviroment" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Enviroment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Enviroment\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnviroment\fP ()"
.br
.ti -1c
.RI "\fB~Enviroment\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file Enviroment\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Enviroment::Enviroment ()"

.PP
Definition at line 4 of file Enviroment\&.cpp\&.
.SS "Enviroment::~Enviroment ()"

.PP
Definition at line 8 of file Enviroment\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
