.TH "ResearchProject/Enviroment.h" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/Enviroment.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnviroment\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
