.TH "ResearchProject/Gui.h" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/Gui.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGUI\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
