.TH "ResearchProject/main.cpp" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'RichText\&.h'\fP
.br
\fC#include 'System\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "main enrtry point "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
main enrtry point 
.PP
\fBReturns\fP
.RS 4
success or failure
.RE
.PP

.PP
Definition at line 26 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
