.TH "ResearchProject/NPC.h" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/NPC.h
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'RichText\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <random>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <array>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNPC\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
