.TH "ResearchProject/RichText.h" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/RichText.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <SFML/Graphics/Transformable\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Drawable\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Color\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Text\&.hpp>\fP
.br
\fC#include <SFML/System/Vector2\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsf::Rect< T >\fP"
.br
.ti -1c
.RI "struct \fBsfe::TextStroke\fP"
.br
.ti -1c
.RI "struct \fBsfe::Outline\fP"
.br
.ti -1c
.RI "class \fBsfe::RichText\fP"
.br
.ti -1c
.RI "class \fBsfe::RichText::Line\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsf\fP"
.br
.ti -1c
.RI " \fBsfe\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Rect< float > \fBsf::FloatRect\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
