.TH "ResearchProject/RichText.cpp" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/RichText.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <cassert>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'RichText\&.h'\fP
.br
\fC#include <SFML/Graphics/Font\&.hpp>\fP
.br
\fC#include <SFML/Graphics/Rect\&.hpp>\fP
.br
\fC#include <SFML/Graphics/RenderTarget\&.hpp>\fP
.br
\fC#include <SFML/System/String\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBsfe\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< sf::String > \fBsfe::explode\fP (const sf::String &string, sf::Uint32 delimiter)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
