.TH "sf" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRect\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBRect\fP< float > \fBFloatRect\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBRect\fP<float> \fBsf::FloatRect\fP"

.PP
Definition at line 21 of file RichText\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
