.TH "sf::Rect< T >" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sf::Rect< T >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RichText\&.h>\fP
.SH "Detailed Description"
.PP 

.SS "template<class T>
.br
class sf::Rect< T >"

.PP
Definition at line 20 of file RichText\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
