.TH "sfe" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sfe
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOutline\fP"
.br
.ti -1c
.RI "class \fBRichText\fP"
.br
.ti -1c
.RI "struct \fBTextStroke\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::vector< sf::String > \fBexplode\fP (const sf::String &string, sf::Uint32 delimiter)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::vector<sf::String> sfe::explode (const sf::String & string, sf::Uint32 delimiter)"

.PP
Definition at line 255 of file RichText\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
