.TH "sfe::Outline" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sfe::Outline
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RichText\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "sf::Color \fBoutline\fP = sf::Color::Transparent"
.br
.ti -1c
.RI "float \fBthickness\fP = 0\&.f"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file RichText\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "sf::Color sfe::Outline::outline = sf::Color::Transparent"

.PP
Definition at line 35 of file RichText\&.h\&.
.SS "float sfe::Outline::thickness = 0\&.f"

.PP
Definition at line 36 of file RichText\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
