.TH "System" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
System
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <System\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSystem\fP ()"
.br
.RI "default constructor setup the window properties load and setup the text load and setup thne image "
.ti -1c
.RI "\fB~System\fP ()"
.br
.RI "default destructor "
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "main \fBSystem\fP loop update 60 times per second, "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSTATES\fP \fBm_currentState\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file System\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "System::System ()"

.PP
default constructor setup the window properties load and setup the text load and setup thne image 
.PP
Definition at line 17 of file System\&.cpp\&.
.SS "System::~System ()"

.PP
default destructor 
.PP
Definition at line 56 of file System\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void System::run ()"

.PP
main \fBSystem\fP loop update 60 times per second, 
.PP
Definition at line 64 of file System\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBSTATES\fP System::m_currentState"

.PP
Definition at line 24 of file System\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
