.TH "ResearchProject/System.h" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/System.h
.SH SYNOPSIS
.br
.PP
\fC#include 'RichText\&.h'\fP
.br
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'tinyxml2\&.h'\fP
.br
\fC#include <random>\fP
.br
\fC#include <array>\fP
.br
\fC#include 'NPC\&.h'\fP
.br
\fC#include 'Gui\&.h'\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSystem\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSTATES\fP { \fBm_startingScreen\fP, \fBm_mainScreen\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSTATES\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIm_startingScreen \fP\fP
.TP
\fB\fIm_mainScreen \fP\fP
.PP
Definition at line 16 of file System\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
