.TH "ResearchProject/System.cpp" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/System.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'System\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include 'tinyxml2\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
