.TH "tinyxml2::XMLUnknown" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tinyxml2::XMLUnknown
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyxml2\&.h>\fP
.PP
Inherits \fBtinyxml2::XMLNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBXMLUnknown\fP * \fBToUnknown\fP ()"
.br
.RI "Safely cast to an Unknown, or null\&. "
.ti -1c
.RI "virtual const \fBXMLUnknown\fP * \fBToUnknown\fP () const"
.br
.ti -1c
.RI "virtual bool \fBAccept\fP (\fBXMLVisitor\fP *visitor) const"
.br
.ti -1c
.RI "virtual \fBXMLNode\fP * \fBShallowClone\fP (\fBXMLDocument\fP *document) const"
.br
.ti -1c
.RI "virtual bool \fBShallowEqual\fP (const \fBXMLNode\fP *compare) const"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBXMLUnknown\fP (\fBXMLDocument\fP *doc)"
.br
.ti -1c
.RI "virtual \fB~XMLUnknown\fP ()"
.br
.ti -1c
.RI "char * \fBParseDeep\fP (char *p, \fBStrPair\fP *parentEndTag, int *curLineNumPtr)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBXMLDocument\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Any tag that TinyXML-2 doesn't recognize is saved as an unknown\&. It is a tag of text, but should not be modified\&. It will be written back to the XML, unchanged, when the file is saved\&. DTD tags get thrown into XMLUnknowns\&. 
.PP
Definition at line 1069 of file tinyxml2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tinyxml2::XMLUnknown::XMLUnknown (\fBXMLDocument\fP * doc)\fC [explicit]\fP, \fC [protected]\fP"

.PP
Definition at line 1331 of file tinyxml2\&.cpp\&.
.SS "tinyxml2::XMLUnknown::~XMLUnknown ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Definition at line 1336 of file tinyxml2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool tinyxml2::XMLUnknown::Accept (\fBXMLVisitor\fP * visitor) const\fC [virtual]\fP"
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM\&. Every node in the XML tree will be conditionally visited and the host will be called back via the \fBXMLVisitor\fP interface\&. This is essentially a SAX interface for TinyXML-2\&. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other\&.) The interface has been based on ideas from:
.IP "\(bu" 2
http://www.saxproject.org/
.IP "\(bu" 2
http://c2.com/cgi/wiki?HierarchicalVisitorPattern Which are both good references for 'visiting'\&. An example of using \fBAccept()\fP: 
.PP
.nf
XMLPrinter printer;
tinyxmlDoc.Accept( &printer );
const char* xmlcstr = printer.CStr();

.fi
.PP
 
.PP

.PP
Implements \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1370 of file tinyxml2\&.cpp\&.
.SS "char * tinyxml2::XMLUnknown::ParseDeep (char * p, \fBStrPair\fP * parentEndTag, int * curLineNumPtr)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1341 of file tinyxml2\&.cpp\&.
.SS "\fBXMLNode\fP * tinyxml2::XMLUnknown::ShallowClone (\fBXMLDocument\fP * document) const\fC [virtual]\fP"
Make a copy of this node, but not its children\&. You may pass in a Document pointer that will be the owner of the new Node\&. If the 'document' is null, then the node returned will be allocated from the current Document\&. (this->\fBGetDocument()\fP) Note: if called on a \fBXMLDocument\fP, this will return null\&. 
.PP
Implements \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1352 of file tinyxml2\&.cpp\&.
.SS "bool tinyxml2::XMLUnknown::ShallowEqual (const \fBXMLNode\fP * compare) const\fC [virtual]\fP"
Test if 2 nodes are the same, but don't test children\&. The 2 nodes do not need to be in the same Document\&. Note: if called on a \fBXMLDocument\fP, this will return false\&. 
.PP
Implements \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1362 of file tinyxml2\&.cpp\&.
.SS "virtual \fBXMLUnknown\fP* tinyxml2::XMLUnknown::ToUnknown ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Safely cast to an Unknown, or null\&. 
.PP
Reimplemented from \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1073 of file tinyxml2\&.h\&.
.SS "virtual const \fBXMLUnknown\fP* tinyxml2::XMLUnknown::ToUnknown () const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBtinyxml2::XMLNode\fP\&.
.PP
Definition at line 1076 of file tinyxml2\&.h\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBXMLDocument\fP\fC [friend]\fP"

.PP
Definition at line 1071 of file tinyxml2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
