.TH "ResearchProject/tinyxml2.cpp" 3 "Wed Apr 29 2020" "Version 1" "Research Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResearchProject/tinyxml2.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'tinyxml2\&.h'\fP
.br
\fC#include <new>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <cstdarg>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtinyxml2::Entity\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtinyxml2\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTIXML_SNPRINTF\fP   snprintf"
.br
.ti -1c
.RI "#define \fBTIXML_VSNPRINTF\fP   vsnprintf"
.br
.ti -1c
.RI "#define \fBTIXML_SSCANF\fP   sscanf"
.br
.ti -1c
.RI "#define \fBTIXML_FSEEK\fP   fseek"
.br
.ti -1c
.RI "#define \fBTIXML_FTELL\fP   ftell"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TIXML_FSEEK   fseek"

.PP
Definition at line 109 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_FTELL   ftell"

.PP
Definition at line 110 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_SNPRINTF   snprintf"

.PP
Definition at line 88 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_SSCANF   sscanf"

.PP
Definition at line 96 of file tinyxml2\&.cpp\&.
.SS "#define TIXML_VSNPRINTF   vsnprintf"

.PP
Definition at line 89 of file tinyxml2\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Research Project from the source code\&.
